[project]
name = "cv-analyzer-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.5.1",
    "pypdf2>=3.0.1",
    "streamlit>=1.51.0",
]
